<?php

return [
    'home' => [
        'label' => 'Page d\'accueil',
        'fields' => [
            'home.hero.eyebrow' => ['label' => 'Hero · bandeau', 'type' => 'text'],
            'home.hero.title' => ['label' => 'Hero · titre', 'type' => 'html'],
            'home.hero.lead' => ['label' => 'Hero · texte', 'type' => 'html'],
            'home.hero.video_poster' => ['label' => 'Hero · poster vidéo', 'type' => 'image'],
            'home.hero.cta_primary' => ['label' => 'Hero · bouton principal', 'type' => 'text'],
            'home.hero.cta_secondary' => ['label' => 'Hero · bouton secondaire', 'type' => 'text'],
            'home.partners.title' => ['label' => 'Partenaires · titre', 'type' => 'text'],
            'home.manifeste.title' => ['label' => 'Manifeste · titre', 'type' => 'text'],
            'home.manifeste.p1' => ['label' => 'Manifeste · paragraphe 1', 'type' => 'html'],
            'home.manifeste.p2' => ['label' => 'Manifeste · paragraphe 2', 'type' => 'html'],
            'home.manifeste.p3' => ['label' => 'Manifeste · mission', 'type' => 'html'],
            'home.manifeste.img1' => ['label' => 'Manifeste · image 1', 'type' => 'image'],
            'home.manifeste.img2' => ['label' => 'Manifeste · image 2', 'type' => 'image'],
            'home.manifeste.img3' => ['label' => 'Manifeste · image 3', 'type' => 'image'],
            'home.catalogue.title' => ['label' => 'Catalogue · titre', 'type' => 'text'],
            'home.catalogue.lead' => ['label' => 'Catalogue · intro', 'type' => 'textarea'],
            'home.discover.title' => ['label' => 'Découvrir · titre', 'type' => 'text'],
            'home.discover.lead' => ['label' => 'Découvrir · intro', 'type' => 'textarea'],
            'home.stats.title' => ['label' => 'Chiffres · titre', 'type' => 'text'],
            'home.stats.items' => ['label' => 'Chiffres · JSON', 'type' => 'json'],
            'home.faq.title' => ['label' => 'FAQ · titre', 'type' => 'text'],
            'home.faq.lead' => ['label' => 'FAQ · intro', 'type' => 'textarea'],
            'home.faq.items' => ['label' => 'FAQ · questions', 'type' => 'json'],
            'home.gallery.title' => ['label' => 'Galerie · titre', 'type' => 'text'],
            'home.gallery.lead' => ['label' => 'Galerie · intro', 'type' => 'textarea'],
            'home.gallery.items' => ['label' => 'Galerie · photos JSON', 'type' => 'json'],
        ],
    ],
    'about' => [
        'label' => 'À propos',
        'fields' => [
            'about.hero.title' => ['label' => 'Hero · titre', 'type' => 'text'],
            'about.hero.lead' => ['label' => 'Hero · chapô', 'type' => 'textarea'],
            'about.intro.title' => ['label' => 'Intro · titre', 'type' => 'text'],
            'about.intro.body' => ['label' => 'Intro · texte', 'type' => 'html'],
            'about.intro.img_top' => ['label' => 'Intro · photo haut', 'type' => 'image'],
            'about.intro.img_bottom' => ['label' => 'Intro · photo bas', 'type' => 'image'],
            'about.highlights' => ['label' => 'Intro · points forts JSON', 'type' => 'json'],
            'about.mission.title' => ['label' => 'Mission · titre section', 'type' => 'text'],
            'about.mission.lead' => ['label' => 'Mission · chapô', 'type' => 'textarea'],
            'about.mission.cards' => ['label' => 'Mission · cartes JSON', 'type' => 'json'],
            'about.timeline.title' => ['label' => 'Parcours · titre', 'type' => 'text'],
            'about.timeline.lead' => ['label' => 'Parcours · chapô', 'type' => 'textarea'],
            'about.timeline.steps' => ['label' => 'Parcours · étapes JSON', 'type' => 'json'],
            'about.team.title' => ['label' => 'Équipe · titre', 'type' => 'text'],
            'about.team.lead' => ['label' => 'Équipe · chapô', 'type' => 'textarea'],
            'about.team.members' => ['label' => 'Équipe · membres JSON', 'type' => 'json'],
            'about.faq.title' => ['label' => 'FAQ · titre', 'type' => 'text'],
            'about.faq.lead' => ['label' => 'FAQ · chapô', 'type' => 'textarea'],
            'about.faq.items' => ['label' => 'FAQ · items JSON', 'type' => 'json'],
            'about.director.title' => ['label' => 'Direction · titre', 'type' => 'text'],
            'about.director.quote' => ['label' => 'Direction · citation', 'type' => 'html'],
            'about.director.name' => ['label' => 'Direction · nom', 'type' => 'text'],
            'about.director.role' => ['label' => 'Direction · rôle', 'type' => 'text'],
            'about.director.image' => ['label' => 'Direction · photo', 'type' => 'image'],
            'about.zero.title' => ['label' => 'Zéro déchet · titre', 'type' => 'text'],
            'about.zero.lead' => ['label' => 'Zéro déchet · texte', 'type' => 'html'],
            'about.zero.flows' => ['label' => 'Zéro déchet · flux JSON', 'type' => 'json'],
            'about.zero.tandem_title' => ['label' => 'Zéro déchet · tandem titre', 'type' => 'text'],
            'about.zero.tandem_text' => ['label' => 'Zéro déchet · tandem texte', 'type' => 'html'],
            'about.zero.tandem_img1' => ['label' => 'Zéro déchet · photo 1', 'type' => 'image'],
            'about.zero.tandem_img2' => ['label' => 'Zéro déchet · photo 2', 'type' => 'image'],
        ],
    ],
    'contact' => [
        'label' => 'Contact',
        'fields' => [
            'contact.hero.title' => ['label' => 'Hero · titre', 'type' => 'text'],
            'contact.hero.lead' => ['label' => 'Hero · chapô', 'type' => 'textarea'],
            'contact.coords.title' => ['label' => 'Coordonnées · titre', 'type' => 'text'],
            'contact.coords.lead' => ['label' => 'Coordonnées · texte', 'type' => 'textarea'],
            'contact.phone' => ['label' => 'Téléphone', 'type' => 'text'],
            'contact.email' => ['label' => 'E-mail', 'type' => 'text'],
            'contact.address' => ['label' => 'Adresse', 'type' => 'text'],
            'contact.form.title' => ['label' => 'Formulaire · titre', 'type' => 'text'],
            'contact.form.lead' => ['label' => 'Formulaire · intro', 'type' => 'textarea'],
            'contact.visual_image' => ['label' => 'Image latérale', 'type' => 'image'],
            'contact.map.title' => ['label' => 'Carte · titre', 'type' => 'text'],
            'contact.map.lead' => ['label' => 'Carte · chapô', 'type' => 'textarea'],
        ],
    ],
    'partner' => [
        'label' => 'Partenaire',
        'fields' => [
            'partner.hero.title' => ['label' => 'Hero · titre', 'type' => 'text'],
            'partner.hero.lead' => ['label' => 'Hero · chapô', 'type' => 'textarea'],
            'partner.types' => ['label' => 'Types partenariat JSON', 'type' => 'json'],
            'partner.form.title' => ['label' => 'Formulaire · titre', 'type' => 'text'],
            'partner.form.lead' => ['label' => 'Formulaire · intro', 'type' => 'textarea'],
            'partner.image' => ['label' => 'Image', 'type' => 'image'],
            'partner.quote' => ['label' => 'Citation', 'type' => 'textarea'],
        ],
    ],
];
